language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - 3.5
env:
  - DJANGO=1.5.12
  - DJANGO=1.6.11
  - DJANGO=1.7.7
  - DJANGO=1.8
  - DJANGO=1.9
  - DJANGO=1.10
matrix:
  exclude:
   - python: 2.6
     env: DJANGO=1.7.7
   - python: 2.6
     env: DJANGO=1.8
   - python: 2.6
     env: DJANGO=1.9
   - python: 2.6
     env: DJANGO=1.10
   - python: 3.3
     env: DJANGO=1.9
   - python: 3.3
     env: DJANGO=1.10
   - python: 3.5
     env: DJANGO=1.5.12
   - python: 3.5
     env: DJANGO=1.6.11
   - python: 3.5
     env: DJANGO=1.7.7
install: pip install -q Django==$DJANGO six coveralls
script: python setup.py coverage
after_success: cd testproject && coveralls
